# This file was generated by GoReleaser. DO NOT EDIT.
cask "todoer" do
  version "1.5.0"

  on_macos do
    on_intel do
      sha256 "674cb176c30faf558e68c8d1a1b5a3c4c08e8680cc4e3da809b4cfe97a11a0d1"
      url "https://github.com/fazil-syed/todoer/releases/download/v#{version}/todoer_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f91e9f31bd81f15cfb7d5feb84cb837ed27ccecd9c594a21d497ef3e4bd1484a"
      url "https://github.com/fazil-syed/todoer/releases/download/v#{version}/todoer_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "35fd25aa2f45df8e7dedb70556cce0cf42fa20afc7b899bc14fef2d7a9d359db"
      url "https://github.com/fazil-syed/todoer/releases/download/v#{version}/todoer_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "94b5f9360a84f499e7eafa1ed1dc1c2c698f94dbfa3d4a88f25c4fc21bee0350"
      url "https://github.com/fazil-syed/todoer/releases/download/v#{version}/todoer_Linux_arm64.tar.gz"
    end
  end

  name "todoer"
  desc ""
  homepage "https://github.com/fazil-syed/todoer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "todoer"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/todoer"]
    end
  end

  # No zap stanza required

end
