# This file was generated by GoReleaser. DO NOT EDIT.
cask "todoer" do
  version "1.4.2"

  on_macos do
    on_intel do
      sha256 "96dcf13bbbad39dd6b3008b717998d77deb9984759147c3c35ad255f15b14cc5"
      url "https://github.com/fazil-syed/todoer/releases/download/v#{version}/todoer_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2d9de4bb02c6e14e1c48e815d56a22feb569d1d7835314c991ac24517edf2a57"
      url "https://github.com/fazil-syed/todoer/releases/download/v#{version}/todoer_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "01735aeb5286966eea01be2f63fcfca59cf1dbde4741ae286c4ae34c7271f8cb"
      url "https://github.com/fazil-syed/todoer/releases/download/v#{version}/todoer_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "697cb97c59ffc5095b6d4321eda16fc7410c0a9200578b6509ca881001f76f17"
      url "https://github.com/fazil-syed/todoer/releases/download/v#{version}/todoer_Linux_arm64.tar.gz"
    end
  end

  name "todoer"
  desc ""
  homepage "https://github.com/fazil-syed/todoer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "todoer"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/todoer"]
    end
  end

  # No zap stanza required

end
