# This file was generated by GoReleaser. DO NOT EDIT.
cask "todoer" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "01071de0f7caa2724ee6fdc6da0549de84ba254837a1130195c9fd037f76a3d3"
      url "https://github.com/fazil-syed/todoer/releases/download/v#{version}/todoer_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6699a859136db79b91f2a167dee5e9d9db3e06e857b5d11ce082fe760f06fe61"
      url "https://github.com/fazil-syed/todoer/releases/download/v#{version}/todoer_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b894a71efa2537909b00e391ebcff926f3d69e21666089142f8cef9ae3483b0d"
      url "https://github.com/fazil-syed/todoer/releases/download/v#{version}/todoer_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8e755d143e5d4fec4bcf129d238224253c2b9ad89433109c8a4281a76a42054f"
      url "https://github.com/fazil-syed/todoer/releases/download/v#{version}/todoer_Linux_arm64.tar.gz"
    end
  end

  name "todoer"
  desc ""
  homepage "https://github.com/fazil-syed/todoer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "todoer"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/todoer"]
    end
  end

  # No zap stanza required

end
